name: Release Beta

on:
  push:
    branches:
      - release-beta
    paths-ignore:
      - 'docs/**'
      - 'README.md'

env:
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}

jobs:
  release_beta_skip_validation:
    name: "Release Beta"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: |
          mkdir sfdx
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz | tar xJ -C sfdx --strip-components 1
          echo $(realpath sfdx/bin) >> $GITHUB_PATH
      - name: Authenticate Dev Hub
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - name: Release Beta
        run: |
          cci org info beta
          cci flow run release_2gp_beta --org beta -o create_package_version__skip_validation false
          cci flow run ci_beta --org beta
          cci org info beta
      - name: Handle Failure
        if: ${{ failure() }}
        run: |
          cci org remove --org beta
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'GutHub Actions'
          SLACK_CHANNEL: jam-ci
          SLACK_COLOR: 'yellow'
          SLACK_ICON_EMOJI: ':cooking:'
          SLACK_MESSAGE: 'jam Beta Release :rocket:'
          SLACK_TITLE: jam BETA